[jobs.fix]
command = [
    "sh",
    "-c",
    "cargo fix --broken-code --allow-dirty && cargo clippy --fix --allow-dirty --quiet >/dev/null 2>&1",
]
need_stdout = true
allow_warnings = true
watch = ["src/**"]
